---
name: Mise Buildkite Plugin
description: Activate Mise environment
author: https://github.com/nkvoll
requirements: []
configuration:
  type: object
  additionalProperties: false
  properties:
    trust:
      type: boolean
      default: true
      description: Trust the mise.toml file.
    install:
      type: boolean
      default: true
      description: Install the tools specified in the mise.toml file.
    activate:
      type: boolean
      default: true
      description: Activate the tools specified in the mise.toml file.
    activate_shims:
      type: boolean
      default: true
      description: Activate using --shims.
