---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "🔄 Triggering pipelines"
    plugins:
      monorepo-diff#v1.5.1:
        diff: ".buildkite/diff ${BUILDKITE_COMMIT}"
        wait: true
        watch:
          # if our Renovate configuration is amended, then make sure we have well-formed config
          # for more info, see https://docs.elastic.dev/plat-prod-team/service-catalogue/renovate/testing-renovate-changes
          - path: "renovate.json"
            config:
              label: "Verify Renovate configuration"
              command: "renovate-config-validator"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.22.0@sha256:25503116fb91c18383b17aee528b9ca6e520ef58622c7f961c7d255bb8ba51f6"
          # if our catalog-info.yaml is changed, make sure it's well-formed according to our internal standards as well as Backstage's validation
          - path: "catalog-info.yaml"
            config:
              command: "/agent/check-catalog-info.sh"
              agents:
                image: "docker.elastic.co/ci-agent-images/pipelib:0.22.0@sha256:25503116fb91c18383b17aee528b9ca6e520ef58622c7f961c7d255bb8ba51f6"

  - label: "🐚 Lint"
    plugins:
      - elastic/mise#main: ~
    command: |
      yamllint plugin.yml

  - label: "🧪 Test"
    plugins:
      elastic/mise#main: ~
    command: |
      yq --version

  - label: "🔬 pre-commit"
    plugins:
      elastic/mise#main: ~
    command: |
      pre-commit run --all
