#!/bin/bash
# Copyright 2025 Elasticsearch B.V.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

echo "--- Init mise-en-place"

export MISE_VERSION="${BUILDKITE_PLUGIN_MISE_VERSION:-}"

curl https://mise.run | sh

export PATH=$PATH:~/.local/bin

echo "Installed mise version: $(mise --version)"

export MISE_ENV="${BUILDKITE_PLUGIN_MISE_ENV:-}"

echo "Set MISE_ENV: ${MISE_ENV}"

if [ "${BUILDKITE_PLUGIN_MISE_TRUST:-true}" != "false" ]; then
  # seems to be needed for tests, but not during actual builds?
  echo "Running: mise trust -a"
  mise trust -a
fi

if [ "${BUILDKITE_PLUGIN_MISE_ACTIVATE:-true}" != "false" ]; then
  echo "Running: mise activate"
  eval "$(mise activate)"
fi

# support --shims
if [ "${BUILDKITE_PLUGIN_MISE_ACTIVATE_SHIMS:-true}" != "false" ]; then
  echo "Running: mise activate --shims"
  eval "$(mise activate --shims)"
fi

if [ "${BUILDKITE_PLUGIN_MISE_INSTALL:-true}" != "false" ]; then
  echo "Running: mise install"
  mise install
fi

mise ls

if [ "${BUILDKITE_PLUGIN_MISE_REDACT:-true}" != "false" ]; then
  echo "Adding redactors"
  for value in $(mise env --redacted --values); do
    echo "$value" | buildkite-agent redactor add
  done
fi

echo "mise-en-place buildkite plugin setup complete"
