#!/bin/bash
set -euo pipefail

echo "--- Init mise-en-place"

curl https://mise.run | sh

export PATH=$PATH:~/.local/bin

export MISE_ENV="${BUILDKITE_PLUGIN_MISE_ENV:-}"

echo "Set MISE_ENV: ${MISE_ENV}"

if [ "${BUILDKITE_PLUGIN_MISE_TRUST:-true}" != "false" ]; then
  # seems to be needed for tests, but not during actual builds?
  echo "Running: mise trust -a"
  mise trust -a
fi

if [ "${BUILDKITE_PLUGIN_MISE_ACTIVATE:-true}" != "false" ]; then
  # support --shims
  if [ "${BUILDKITE_PLUGIN_MISE_ACTIVATE_SHIMS:-true}" != "false" ]; then
    echo "Running: mise activate --shims"
    eval "$(mise activate --shims)"
    export PATH=$PATH:/root/.local/share/mise/shims
  else
    echo "Running: mise activate"
    eval "$(mise activate)"
  fi
fi

if [ "${BUILDKITE_PLUGIN_MISE_INSTALL:-true}" != "false" ]; then
  echo "Running: mise install"
  mise install
fi

mise ls

if [ "${BUILDKITE_PLUGIN_MISE_REDACT:-true}" != "false" ]; then
  echo "Adding redactors"
  for value in $(mise env --redacted --values); do
    echo "$value" | buildkite-agent redactor add
  done
fi

echo "Installed mise version: $(mise --version)"
